[workspace]
authors = ["AshinTheAnvil <ashinanand66@gmail.com>"]
channels = ["robostack-jazzy", "conda-forge"]
name = "pixi_rox"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[activation]
scripts = ["install/setup.sh"]


[dependencies]
ros-jazzy-desktop = ">=0.11.0,<0.12"
ros-jazzy-ros-gz-sim = ">=1.0.16,<2"
ros-jazzy-ros-gz-bridge = ">=1.0.16,<2"
ros-jazzy-topic-tools = ">=1.3.3,<2"
